version: "3.8"
services:
  ui:
    container_name: "parrot-ui"
    build: .
    ports:
      - "4200:80"
    #environment:
    #  - BACKEND_BASE_PATH=http://localhost:8000
    #depends_on:
    #  - backend
    